services:
  tailscale-pysrv:
    image: tailscale/tailscale:latest
    hostname: tailscale-pysrv
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_USERSPACE=false
    # volumes:
    #   - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  pysrv:
    build:
      context: .
    depends_on:
      - tailscale-pysrv
    network_mode: service:tailscale-pysrv
